package template;

import com.google.zxing.WriterException;
import dao.ProdutoDAO;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.math.BigDecimal;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.ProdutoModel;
import service.GeradorCodBarrasService;
import service.ValidatorService;

/**
 *
 * @author Juu
 */
public class InternalFrameCadastroProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameCadastroProduto
     */
    public InternalFrameCadastroProduto() {
        initComponents();
        txtCodigoBarras.setText(ProdutoModel.generateBarCodeEAN13());
        
        BufferedImage imagemCodigo;
        try {
            imagemCodigo = GeradorCodBarrasService.gerarCodigoBarrasEAN13(txtCodigoBarras.getText().substring(0, 12));
            lblBarcode.setIcon(new ImageIcon(imagemCodigo));
            lblBarcode.setText(""); // remove o texto padrão
        } catch (WriterException e) {
            lblBarcode.setText("Erro ao gerar código.");
            e.printStackTrace();
        }
            
        ValidatorService validator = new ValidatorService();
        
        txtEstoque.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validator.onlyNumber(evt); // Chama o método para impedir letras
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        lblCodigoBarras = new javax.swing.JLabel();
        lblNomeProduto = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblEstoque = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        txtNomeProduto = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtEstoque = new javax.swing.JTextField();
        cbxCategoria = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblAviso = new javax.swing.JLabel();
        lblAviso1 = new javax.swing.JLabel();
        lblBarcode = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jTextField6.setText("jTextField6");

        setPreferredSize(new java.awt.Dimension(960, 733));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(13, 45, 89));
        lblTitulo.setText("Cadastro de Produto");

        lblCodigoBarras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodigoBarras.setForeground(new java.awt.Color(13, 45, 89));
        lblCodigoBarras.setText("Código de barras");

        lblNomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomeProduto.setForeground(new java.awt.Color(13, 45, 89));
        lblNomeProduto.setText("Nome do produto");

        lblPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPreco.setForeground(new java.awt.Color(13, 45, 89));
        lblPreco.setText("Preço");

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(13, 45, 89));
        lblCategoria.setText("Categoria");

        lblEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstoque.setForeground(new java.awt.Color(13, 45, 89));
        lblEstoque.setText("Estoque");

        txtCodigoBarras.setEditable(false);
        txtCodigoBarras.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBarrasActionPerformed(evt);
            }
        });

        txtNomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomeProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 45, 89), 2));
        txtNomeProduto.setName("Nome do produto"); // NOI18N

        txtPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 45, 89), 2));
        txtPreco.setName("Preço"); // NOI18N

        txtEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEstoque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 45, 89), 2));
        txtEstoque.setName("Estoque"); // NOI18N

        cbxCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Selecione uma opção -", "Livros", "Chaveiros", "Bálsamos", "Broches", "Enfeites" }));
        cbxCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 45, 89), 2));
        cbxCategoria.setName("Categoria"); // NOI18N

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(13, 45, 89));
        btnCancel.setText("Cancelar");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 45, 89)));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(13, 45, 89));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Cadastrar");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblAviso.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblAviso.setForeground(new java.awt.Color(13, 45, 89));
        lblAviso.setText("O código é gerado automaticamente pelo sistema e não pode ser alterado.");

        lblAviso1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblAviso1.setForeground(new java.awt.Color(13, 45, 89));
        lblAviso1.setText("Cadastrar o preço com . (Ex: 100.99)");

        lblBarcode.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblNomeProduto)
                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoBarras)
                            .addComponent(lblAviso, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(txtEstoque)
                        .addComponent(lblEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAviso1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblCategoria)
                        .addComponent(cbxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPreco)))
                .addGap(0, 277, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(lblBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblCodigoBarras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAviso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(lblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAviso1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBarrasActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        try {
            ValidatorService validator = new ValidatorService();
            validator.validateNullField(txtNomeProduto);
            validator.validateNullField(txtEstoque);
            validator.validatePrice(txtPreco);
            validator.validateComboBox(cbxCategoria);
            
            if (validator.hasErro()) {
                JOptionPane.showMessageDialog(rootPane, "Não foi possível cadastrar o produto!");
                JOptionPane.showMessageDialog(rootPane, validator.getMensagensErro());
                return;
            }
            
            ProdutoModel p = new ProdutoModel();
       
            p.setNome(txtNomeProduto.getText());
            p.setCategoria(cbxCategoria.getSelectedItem().toString());
            p.setPreco(new BigDecimal(txtPreco.getText()));
            p.setEstoque(Integer.parseInt(txtEstoque.getText()));
            p.setCodigoBarras(txtCodigoBarras.getText());

            ProdutoDAO dao = new ProdutoDAO();
            dao.save(p);

            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");
            this.dispose();
       } catch (HeadlessException | NumberFormatException e) {
           e.printStackTrace();
           JOptionPane.showMessageDialog(this, "Erro ao cadastrar produto: " + e.getMessage());
       }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblAviso1;
    private javax.swing.JLabel lblBarcode;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}