package template;

import dao.ProdutoDAO;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JDesktopPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.ProdutoModel;
/**
 *
 * @author jeff_
 */
public class InternalFrameVenda extends javax.swing.JInternalFrame {

    private JDesktopPane desktop;
    private ProdutoModel produtoAtual;

    /**
     * Creates new form InternalFrameVenda
     */
    public InternalFrameVenda(JDesktopPane desktop) {
        initComponents();
        this.desktop = desktop;
        
        txtBarCodeSearch.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String codigoBarras = txtBarCodeSearch.getText().trim();
                        
                if (codigoBarras.length() == 13) {
                    ProdutoDAO dao = new ProdutoDAO();
                    produtoAtual = dao.findByCodigoBarras(codigoBarras);
                    
                    if (produtoAtual != null) {
                        txtNomeProduto.setText(produtoAtual.getNome());
                        txtEstoqueAtual.setText(String.valueOf(produtoAtual.getEstoque()));
                    }
                }
            }
        });
        setTableDesign(tblVendas);
    }
    
    public void setTableDesign(JTable table) {
        // Centraliza cabeçalhos
        ((javax.swing.table.DefaultTableCellRenderer) table.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        // Centraliza valores
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        table.getColumnModel().getColumn(0).setCellRenderer(centerRenderer); // Código
        table.getColumnModel().getColumn(2).setCellRenderer(centerRenderer); // Preço
        table.getColumnModel().getColumn(3).setCellRenderer(centerRenderer); // Quantidade
        table.getColumnModel().getColumn(4).setCellRenderer(centerRenderer); // Preço Total
        
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        table.getTableHeader().setBackground(new Color(13, 45, 89));
        table.getTableHeader().setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton5 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBarCodeSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEstoqueAtual = new javax.swing.JTextField();
        txtQtdVenda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAddItemPedido = new javax.swing.JButton();
        lblTotalVenda = new javax.swing.JLabel();
        lblTotalVenda1 = new javax.swing.JLabel();
        rbPix = new javax.swing.JRadioButton();
        rbCredito = new javax.swing.JRadioButton();
        rbDebito = new javax.swing.JRadioButton();
        rbDinheiro = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        btnDeleteItem = new javax.swing.JButton();

        jRadioButton5.setText("jRadioButton5");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(13, 45, 89));
        jLabel1.setText("Finalizar Venda");

        jLabel2.setText("Insira o código de barras para buscar um produto");

        txtBarCodeSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBarCodeSearch.setToolTipText("");
        txtBarCodeSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 45, 89), 2));
        txtBarCodeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarCodeSearchActionPerformed(evt);
            }
        });

        tblVendas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Preço unitário", "Quantidade", "Preço total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblVendas.setCellSelectionEnabled(true);
        tblVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblVendas.setGridColor(new java.awt.Color(204, 204, 204));
        tblVendas.setSelectionBackground(new java.awt.Color(13, 45, 89));
        tblVendas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tblVendas);

        txtNomeProduto.setEditable(false);
        txtNomeProduto.setBackground(new java.awt.Color(230, 230, 230));
        txtNomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomeProduto.setToolTipText("");
        txtNomeProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 45, 89), 2));
        txtNomeProduto.setEnabled(false);
        txtNomeProduto.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtNomeProduto.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Produto");

        jLabel4.setText("Estoque atual");

        jLabel5.setText("Quantidade da venda");

        txtEstoqueAtual.setEditable(false);
        txtEstoqueAtual.setBackground(new java.awt.Color(230, 230, 230));
        txtEstoqueAtual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEstoqueAtual.setToolTipText("");
        txtEstoqueAtual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 45, 89), 2));
        txtEstoqueAtual.setEnabled(false);
        txtEstoqueAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstoqueAtualActionPerformed(evt);
            }
        });

        txtQtdVenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtQtdVenda.setToolTipText("");
        txtQtdVenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 45, 89), 2));
        txtQtdVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdVendaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(13, 45, 89));
        jLabel6.setText("Itens da venda");

        btnAddItemPedido.setBackground(new java.awt.Color(13, 45, 89));
        btnAddItemPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddItemPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnAddItemPedido.setText("Adicionar à venda ");
        btnAddItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemPedidoActionPerformed(evt);
            }
        });

        lblTotalVenda.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTotalVenda.setForeground(new java.awt.Color(13, 45, 89));
        lblTotalVenda.setText("TOTAL: R$ 0.00");

        lblTotalVenda1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalVenda1.setForeground(new java.awt.Color(13, 45, 89));
        lblTotalVenda1.setText("PAGAMENTO: À DEFINIR");

        rbPix.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbPix);
        rbPix.setText("PIX");
        rbPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPixActionPerformed(evt);
            }
        });

        rbCredito.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbCredito);
        rbCredito.setText("CRÉDITO");

        rbDebito.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbDebito);
        rbDebito.setText("DÉBITO");

        rbDinheiro.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbDinheiro);
        rbDinheiro.setText("DINHEIRO");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(13, 45, 89));
        jLabel7.setText("Forma de pagamento");

        btnDeleteItem.setBackground(new java.awt.Color(13, 45, 89));
        btnDeleteItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteItem.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteItem.setText("Delete");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteItem))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBarCodeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtQtdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbPix)
                                        .addGap(12, 12, 12)
                                        .addComponent(rbCredito)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbDebito)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbDinheiro))
                                    .addComponent(jLabel7))
                                .addGap(305, 305, 305)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotalVenda1)
                                    .addComponent(lblTotalVenda, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddItemPedido)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBarCodeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQtdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(btnAddItemPedido)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnDeleteItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalVenda1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPix)
                            .addComponent(rbCredito)
                            .addComponent(rbDebito)
                            .addComponent(rbDinheiro))))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBarCodeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarCodeSearchActionPerformed
    }//GEN-LAST:event_txtBarCodeSearchActionPerformed

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void txtEstoqueAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueAtualActionPerformed
    }//GEN-LAST:event_txtEstoqueAtualActionPerformed

    private void txtQtdVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdVendaActionPerformed
    }//GEN-LAST:event_txtQtdVendaActionPerformed

    private void btnAddItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemPedidoActionPerformed
        
        if (produtoAtual == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhum produto selecionado!");
            return;
        }
        
        try {
            int qtdItem = Integer.parseInt(txtQtdVenda.getText());
            
            if (qtdItem <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Quantidade não pode ser 0!");
                return;
            }
            
            if (qtdItem > produtoAtual.getEstoque()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Quantidade excede o estoque disponível!");
                return;
            }
            
            BigDecimal precoUnit = produtoAtual.getPreco();
            BigDecimal qtd = new BigDecimal(qtdItem);
            BigDecimal precoTotal = precoUnit.multiply(qtd);
            
            DefaultTableModel model = (DefaultTableModel) tblVendas.getModel();
            model.addRow(new Object[] {
                produtoAtual.getCodigoBarras(),
                produtoAtual.getNome(),
                "R$ " + String.format("%.2f", precoUnit),
                qtd,
                "R$ " + String.format("%.2f", precoTotal),
            });
            
            atualizarTotalVenda();
            
             // Limpa campos
            txtBarCodeSearch.setText("");
            txtNomeProduto.setText("");
            txtEstoqueAtual.setText("");
            txtQtdVenda.setText("");
            produtoAtual = null;
            tblVendas.clearSelection();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantidade inválida.");
        }
    }//GEN-LAST:event_btnAddItemPedidoActionPerformed

    private void atualizarTotalVenda() {
        DefaultTableModel model = (DefaultTableModel) tblVendas.getModel();
        BigDecimal total = BigDecimal.ZERO;
        
        for(int i = 0; i < model.getRowCount(); i++) {
            Object precoTotalObj = model.getValueAt(i, 4);
            
            if (precoTotalObj instanceof String) {
                String valorStr = ((String) precoTotalObj).replace("R$", "").trim().replace(",", ".");
                try {
                    BigDecimal valor = new BigDecimal(valorStr);
                    total = total.add(valor);
                } catch (NumberFormatException e) {
                    
                }
            }
        }
        
        lblTotalVenda.setText("TOTAL: R$ " + total.setScale(2, RoundingMode.HALF_UP));
    }
    
    private void rbPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPixActionPerformed
    }//GEN-LAST:event_rbPixActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        int selectedRow = tblVendas.getSelectedRow();
        
        if(selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um item para remover!");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblVendas.getModel();
        model.removeRow(selectedRow);
        
        atualizarTotalVenda();
    }//GEN-LAST:event_btnDeleteItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItemPedido;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotalVenda;
    private javax.swing.JLabel lblTotalVenda1;
    private javax.swing.JRadioButton rbCredito;
    private javax.swing.JRadioButton rbDebito;
    private javax.swing.JRadioButton rbDinheiro;
    private javax.swing.JRadioButton rbPix;
    private javax.swing.JTable tblVendas;
    private javax.swing.JTextField txtBarCodeSearch;
    private javax.swing.JTextField txtEstoqueAtual;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtQtdVenda;
    // End of variables declaration//GEN-END:variables
}
