/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package template;

import dao.VendaDAO;
import java.awt.Color;
import java.awt.Font;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.VendaModel;
import util.JasperReports;

/**
 *
 * @author jeff_
 */
public class InternalFrameRelatorio extends javax.swing.JInternalFrame {

    private JDesktopPane desktop;
    /**
     * Creates new form InternalFrameRelatorio
     * @param desktop
     */
    public InternalFrameRelatorio(JDesktopPane desktop) {
        initComponents();
        this.desktop = desktop;
        
        VendaDAO dao = new VendaDAO();
        lblQtdVendas.setText(String.valueOf(dao.countVendas()));
        
        BigDecimal totalEmVendas = dao.sumVendas(); 
        String valorFormatado = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("pt","BR")).format(totalEmVendas);
        
        lblTotalVendas.setText(valorFormatado);
        
        loadVendasTable();
   }
    
    public void loadVendasTable() {
        
        VendaDAO dao = new VendaDAO();
        List<VendaModel> vendas = dao.listVendasDesc();
        
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("Data da venda");
        table.addColumn("Preço total");
        table.addColumn("Forma de pagamento");
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");

        for (VendaModel v : vendas) {
            table.addRow(new Object[]{
                sdf.format(v.getDataVenda()),
                "R$ " + String.format("%.2f", v.getTotalVenda()),
                v.getFormaPagamento(),
            });
        }
        tblVendas.setModel(table);
        setTableDesign(tblVendas);

    }
    
    public void setTableDesign(JTable table) {
        
        ((javax.swing.table.DefaultTableCellRenderer) table.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        table.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        table.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        table.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        table.getTableHeader().setBackground(new Color(13, 45, 89));
        table.getTableHeader().setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTitleVendas = new javax.swing.JLabel();
        lblTitleQtdVendas = new javax.swing.JLabel();
        lblQtdVendas = new javax.swing.JLabel();
        lblTotalVendas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        btnGerarRelatorio = new javax.swing.JButton();
        startDatePicker = new com.toedter.calendar.JDateChooser();
        endDatePicker = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(13, 45, 89));
        jLabel1.setText("Relatórios");

        lblTitleVendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitleVendas.setForeground(new java.awt.Color(13, 45, 89));
        lblTitleVendas.setText("Total em vendas nos últimos 30 dias");

        lblTitleQtdVendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitleQtdVendas.setForeground(new java.awt.Color(13, 45, 89));
        lblTitleQtdVendas.setText("Vendas nos últimos 30 dias");

        lblQtdVendas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQtdVendas.setForeground(new java.awt.Color(13, 45, 89));
        lblQtdVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtdVendas.setText("totalVendas");
        lblQtdVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTotalVendas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalVendas.setForeground(new java.awt.Color(13, 45, 89));
        lblTotalVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalVendas.setText("totalEmVendas");
        lblTotalVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tblVendas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data da venda", "Preço total", "Forma de pagamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblVendas.setCellSelectionEnabled(true);
        tblVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblVendas.setGridColor(new java.awt.Color(204, 204, 204));
        tblVendas.setSelectionBackground(new java.awt.Color(13, 45, 89));
        tblVendas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblVendas.getTableHeader().setResizingAllowed(false);
        jScrollPane2.setViewportView(tblVendas);

        btnGerarRelatorio.setBackground(new java.awt.Color(13, 45, 89));
        btnGerarRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGerarRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnGerarRelatorio.setText("Gerar relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(13, 45, 89));
        jLabel2.setText("Data de início");

        jLabel3.setForeground(new java.awt.Color(13, 45, 89));
        jLabel3.setText("até");

        jLabel4.setForeground(new java.awt.Color(13, 45, 89));
        jLabel4.setText("Data final");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(13, 45, 89));
        jLabel6.setText("Filtro de Relatório");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitleQtdVendas)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lblQtdVendas)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTitleVendas)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTotalVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(startDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3)))
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleQtdVendas)
                    .addComponent(lblTitleVendas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdVendas)
                    .addComponent(lblTotalVendas))
                .addGap(93, 93, 93)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(startDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed

        try {
            Date startDate = startDatePicker.getDate();
            Date endDate = endDatePicker.getDate();
            
            if (startDate.compareTo(endDate) > 0) {
                JOptionPane.showMessageDialog(rootPane, "Data de início não pode ser maior que a data final!");
                return;
            }
            
            JasperReports jasper = new JasperReports();
            jasper.gerarRelatorio(startDate, endDate);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Não é possível gerar o relatório sem informar as datas de filtro!");
        }
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarRelatorio;
    private com.toedter.calendar.JDateChooser endDatePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblQtdVendas;
    private javax.swing.JLabel lblTitleQtdVendas;
    private javax.swing.JLabel lblTitleVendas;
    private javax.swing.JLabel lblTotalVendas;
    private com.toedter.calendar.JDateChooser startDatePicker;
    private javax.swing.JTable tblVendas;
    // End of variables declaration//GEN-END:variables
}
