/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package template;

import dao.VendaDAO;
import java.math.BigDecimal;
import javax.swing.JDesktopPane;

/**
 *
 * @author jeff_
 */
public class InternalFrameRelatorio extends javax.swing.JInternalFrame {

    private JDesktopPane desktop;
    /**
     * Creates new form InternalFrameRelatorio
     * @param desktop
     */
    public InternalFrameRelatorio(JDesktopPane desktop) {
        initComponents();
        this.desktop = desktop;
        
        VendaDAO dao = new VendaDAO();
        
        lblQtdVendas.setText(String.valueOf(dao.countVendas()));
        
        BigDecimal totalEmVendas = dao.sumVendas(); 
        String valorFormatado = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("pt","BR")).format(totalEmVendas);
        
        lblTotalVendas.setText(valorFormatado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitleVendas = new javax.swing.JLabel();
        lblTitleQtdVendas = new javax.swing.JLabel();
        lblQtdVendas = new javax.swing.JLabel();
        lblTotalVendas = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(13, 45, 89));
        jLabel1.setText("Relatórios");

        lblTitleVendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitleVendas.setForeground(new java.awt.Color(13, 45, 89));
        lblTitleVendas.setText("Total em vendas nos últimos 30 dias");

        lblTitleQtdVendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitleQtdVendas.setForeground(new java.awt.Color(13, 45, 89));
        lblTitleQtdVendas.setText("Vendas nos últimos 30 dias");

        lblQtdVendas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQtdVendas.setForeground(new java.awt.Color(13, 45, 89));
        lblQtdVendas.setText("jLabel4");

        lblTotalVendas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalVendas.setForeground(new java.awt.Color(13, 45, 89));
        lblTotalVendas.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(268, 748, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitleVendas)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(lblQtdVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalVendas)
                .addGap(262, 262, 262))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(lblTitleQtdVendas)
                    .addContainerGap(636, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(lblTitleVendas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdVendas)
                    .addComponent(lblTotalVendas))
                .addContainerGap(494, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(lblTitleQtdVendas)
                    .addContainerGap(543, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblQtdVendas;
    private javax.swing.JLabel lblTitleQtdVendas;
    private javax.swing.JLabel lblTitleVendas;
    private javax.swing.JLabel lblTotalVendas;
    // End of variables declaration//GEN-END:variables
}
