/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package template;

import dao.ProdutoDAO;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ProdutoModel;
import util.Validator;

/**
 *
 * @author jeffe
 */
public class InternalFrameProduto extends javax.swing.JInternalFrame {
    
    private JDesktopPane desktop;
    private ProdutoDAO produtoDAO = new ProdutoDAO();
    private int paginaAtual = 0;
    private final int tamanhoPagina = 10;
    private int totalPaginas = 0;
    /**
     * Creates new form InternalFrameProduto
     */
    public InternalFrameProduto(JDesktopPane desktop) {
        initComponents();
        this.desktop = desktop;
        Validator validator = new Validator();
        
        txtBarCodeSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validator.barCodeSearchValidate(evt);
            }
        });
        
        loadProductTable();
        
        productsTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        productsTable.getTableHeader().setBackground(new Color(13, 45, 89));
        productsTable.getTableHeader().setForeground(Color.WHITE);
        configurarFiltro();
    }

    private TableRowSorter<TableModel> sorter;

    private void configurarFiltro() {
        sorter = new TableRowSorter<>(productsTable.getModel());
        productsTable.setRowSorter(sorter);

        txtBarCodeSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrar();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrar();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrar();
            }

            private void filtrar() {
                String texto = txtBarCodeSearch.getText();
                if (texto.trim().isEmpty()) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
                }
            }
        });
    }

    public void loadProductTable() {
        List<ProdutoModel> list = produtoDAO.findAllPaged(paginaAtual, tamanhoPagina);
        int totalRegistros = produtoDAO.countAll();
        totalPaginas = (int) Math.ceil((double) totalRegistros / tamanhoPagina);

        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("Código");
        table.addColumn("Nome");
        table.addColumn("Preço");
        table.addColumn("Estoque");
        table.addColumn("Categoria");

        for (ProdutoModel p : list) {
            table.addRow(new Object[]{
                p.getCodigoBarras(),
                p.getNome(),
                "R$ " + String.format("%.2f", p.getPreco()),
                p.getEstoque(),
                p.getCategoria()
            });
        }

        productsTable.setModel(table);
        
        // Centraliza cabeçalhos
        ((javax.swing.table.DefaultTableCellRenderer) productsTable.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        // Centraliza "Código" e "Estoque"
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productsTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer); // Código
        productsTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer); // Preço
        productsTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer); // Estoque
        productsTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer); // Categoria
        
        jLabel3.setText("Página " + (paginaAtual + 1) + " de " + totalPaginas);
        configurarFiltro();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        newProduct = new javax.swing.JButton();
        updateProduct = new javax.swing.JButton();
        txtBarCodeSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(960, 733));

        productsTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Produto", "Preço", "Qtd. Estoque", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        productsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        productsTable.setGridColor(new java.awt.Color(204, 204, 204));
        productsTable.setSelectionBackground(new java.awt.Color(13, 45, 89));
        productsTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(productsTable);

        newProduct.setBackground(new java.awt.Color(13, 45, 89));
        newProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newProduct.setForeground(new java.awt.Color(255, 255, 255));
        newProduct.setText("Cadastrar produto");
        newProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductActionPerformed(evt);
            }
        });

        updateProduct.setBackground(new java.awt.Color(13, 45, 89));
        updateProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateProduct.setForeground(new java.awt.Color(255, 255, 255));
        updateProduct.setText("Atualizar produto");
        updateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductActionPerformed(evt);
            }
        });

        txtBarCodeSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBarCodeSearch.setToolTipText("");

        jLabel1.setText("Insira o código de barras para buscar um produto");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(13, 45, 89));
        jLabel2.setText("Produtos cadastrados no sistema");

        jButton1.setBackground(new java.awt.Color(13, 45, 89));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ANTERIOR <<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(13, 45, 89));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText(">> PRÓXIMO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(13, 45, 89));
        jLabel3.setText("numberOfPages");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(13, 45, 89));
        jLabel4.setText("Gestão de Produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton1)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(200, 200, 200))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtBarCodeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updateProduct)
                                    .addGap(18, 18, 18)
                                    .addComponent(newProduct))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(52, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newProduct)
                    .addComponent(updateProduct)
                    .addComponent(txtBarCodeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductActionPerformed
        this.dispose(); 

        InternalFrameCadastroProduto cadastro = new InternalFrameCadastroProduto();
        desktop.add(cadastro);
        cadastro.setVisible(true);
    }//GEN-LAST:event_newProductActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (paginaAtual > 0) {
            paginaAtual--;
            loadProductTable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (paginaAtual < totalPaginas - 1) {
            paginaAtual++;
            loadProductTable();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductActionPerformed
        String codigoBarras = txtBarCodeSearch.getText().trim();

        if (codigoBarras.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Informe o código de barras para editar.");
            return;
        }

        ProdutoModel produto = produtoDAO.findByCodigoBarras(codigoBarras);

        if (produto != null) {
            this.dispose(); // fecha a tela atual

            InternalFrameAlteracaoProduto alteracao = new InternalFrameAlteracaoProduto(produto);
            desktop.add(alteracao);
            alteracao.setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Produto não encontrado.");
        }
    }//GEN-LAST:event_updateProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton newProduct;
    private javax.swing.JTable productsTable;
    private javax.swing.JTextField txtBarCodeSearch;
    private javax.swing.JButton updateProduct;
    // End of variables declaration//GEN-END:variables
}
