package template;

import dao.ProdutoDAO;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.ProdutoModel;
import service.JasperReportsService;

/**
 *
 * @author jeff_
 */
public class InternalFrameRelatorioProduto extends javax.swing.JInternalFrame {
    
    private JDesktopPane desktop;
    private final ProdutoDAO produtoDAO = new ProdutoDAO();
    private int paginaAtual = 0;
    private final int tamanhoPagina = 20;
    private int totalPaginas = 0;


    /**
     * Creates new form InternalFrameRelatorioProduto
     * @param desktop
     */
    public InternalFrameRelatorioProduto(JDesktopPane desktop) {
        initComponents();
        this.desktop = desktop;
        loadProductTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGerarRelatorio = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        lblTitle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnPagAnterior = new javax.swing.JButton();
        lblTotalPages = new javax.swing.JLabel();
        btnProximaPagina = new javax.swing.JButton();
        btnGerarRelatorioProdutos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rbProdSemEstoque = new javax.swing.JRadioButton();
        rbTodosProd = new javax.swing.JRadioButton();

        btnGerarRelatorio.setBackground(new java.awt.Color(13, 45, 89));
        btnGerarRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGerarRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnGerarRelatorio.setText("Gerar relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        jRadioButton3.setText("jRadioButton3");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(13, 45, 89));
        lblTitle.setText("Relatório de produtos");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(13, 45, 89));
        jLabel7.setText("Listagem de produtos");

        tblProdutos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data da venda", "Preço total", "Forma de pagamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblProdutos.setCellSelectionEnabled(true);
        tblProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblProdutos.setGridColor(new java.awt.Color(204, 204, 204));
        tblProdutos.setSelectionBackground(new java.awt.Color(13, 45, 89));
        tblProdutos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblProdutos.getTableHeader().setResizingAllowed(false);
        jScrollPane2.setViewportView(tblProdutos);

        btnPagAnterior.setBackground(new java.awt.Color(13, 45, 89));
        btnPagAnterior.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPagAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnPagAnterior.setText("ANTERIOR <<");
        btnPagAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagAnteriorActionPerformed(evt);
            }
        });

        lblTotalPages.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalPages.setForeground(new java.awt.Color(13, 45, 89));
        lblTotalPages.setText("numberOfPages");

        btnProximaPagina.setBackground(new java.awt.Color(13, 45, 89));
        btnProximaPagina.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProximaPagina.setForeground(new java.awt.Color(255, 255, 255));
        btnProximaPagina.setText(">> PRÓXIMO");
        btnProximaPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximaPaginaActionPerformed(evt);
            }
        });

        btnGerarRelatorioProdutos.setBackground(new java.awt.Color(13, 45, 89));
        btnGerarRelatorioProdutos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGerarRelatorioProdutos.setForeground(new java.awt.Color(255, 255, 255));
        btnGerarRelatorioProdutos.setText("Gerar relatório");
        btnGerarRelatorioProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioProdutosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(13, 45, 89));
        jLabel6.setText("Filtro de Relatório");

        rbProdSemEstoque.setText("Apenas produtos sem estoque");

        rbTodosProd.setText("Todos os produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(rbProdSemEstoque)
                                        .addComponent(rbTodosProd))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGerarRelatorioProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(btnPagAnterior)
                        .addGap(105, 105, 105)
                        .addComponent(lblTotalPages)
                        .addGap(105, 105, 105)
                        .addComponent(btnProximaPagina)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitle)
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagAnterior)
                    .addComponent(btnProximaPagina)
                    .addComponent(lblTotalPages))
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbProdSemEstoque)
                    .addComponent(btnGerarRelatorioProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbTodosProd)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagAnteriorActionPerformed
        if (paginaAtual > 0) {
            paginaAtual--;
            loadProductTable();
        }
    }//GEN-LAST:event_btnPagAnteriorActionPerformed

    private void btnProximaPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximaPaginaActionPerformed
        if (paginaAtual < totalPaginas - 1) {
            paginaAtual++;
            loadProductTable();
        }
    }//GEN-LAST:event_btnProximaPaginaActionPerformed

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed

    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    private void btnGerarRelatorioProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioProdutosActionPerformed

        try {
            JasperReportsService jasper = new JasperReportsService();
            jasper.gerarRelatorioProduto();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_btnGerarRelatorioProdutosActionPerformed

    public void loadProductTable() {
        List<ProdutoModel> list = produtoDAO.findAllPaged(paginaAtual, tamanhoPagina);
        int totalRegistros = produtoDAO.countAll();
        totalPaginas = (int) Math.ceil((double) totalRegistros / tamanhoPagina);

        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("Nome");
        table.addColumn("Preço");
        table.addColumn("Estoque");
        table.addColumn("Categoria");

        for (ProdutoModel p : list) {
            table.addRow(new Object[]{
                p.getNome(),
                "R$ " + String.format("%.2f", p.getPreco()),
                p.getEstoque(),
                p.getCategoria()
            });
        }

        tblProdutos.setModel(table);
        lblTotalPages.setText("Página " + (paginaAtual + 1) + " de " + totalPaginas);
        setTableDesign(tblProdutos);

    }
    
    public void setTableDesign(JTable table) {
        
        ((javax.swing.table.DefaultTableCellRenderer) table.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        table.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        table.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        table.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        table.getTableHeader().setBackground(new Color(13, 45, 89));
        table.getTableHeader().setForeground(Color.WHITE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JButton btnGerarRelatorioProdutos;
    private javax.swing.JButton btnPagAnterior;
    private javax.swing.JButton btnProximaPagina;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalPages;
    private javax.swing.JRadioButton rbProdSemEstoque;
    private javax.swing.JRadioButton rbTodosProd;
    private javax.swing.JTable tblProdutos;
    // End of variables declaration//GEN-END:variables
}
